version: "3.8"

services:

  web:
    image: tomatto/django-telegram-bot:latest
    container_name: dtb_django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8777"
    volumes:
      - .:/code
    ports:
      - "8777:8777"
    env_file:
      - ./.env
    external_links:
      - Redis
      - postgresql14
    restart: unless-stopped

  bot:
    image: tomatto/django-telegram-bot:latest
    container_name: dtb_bot
    command: python run_pooling.py
    env_file:
      - ./.env
    depends_on:
      - web
    external_links:
      - Redis
      - postgresql14
    restart: unless-stopped

  celery:
    image: tomatto/django-telegram-bot:latest
    container_name: dtb_celery
    command: celery -A dtb worker --loglevel=INFO
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - web
    external_links:
      - Redis
      - postgresql14
    restart: unless-stopped

  celery-beat:
    image: tomatto/django-telegram-bot:latest
    container_name: dtb_beat
    command: celery -A dtb beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - celery
      - web
    external_links:
      - Redis
      - postgresql14
    restart: unless-stopped
