# Generated by Django 3.2.13 on 2022-04-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_screen',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='node_sudo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_port',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
