# Generated by Django 3.2.13 on 2022-04-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20220422_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
