# Generated by Django 3.2.13 on 2022-04-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_auto_20220422_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_screen',
            new_name='screen_name',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='node_sudo',
            new_name='sudo_flag',
        ),
    ]
