# Generated by Django 3.2.13 on 2022-04-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20220422_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkhistory',
            name='status_text',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='last_status_text',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='checkhistory',
            name='status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='last_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
