# Generated by Django 3.2.13 on 2022-05-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_auto_20220424_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkhistory',
            name='reward_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='last_reward_value',
            field=models.IntegerField(default=0),
        ),
    ]
