# Generated by Django 3.2.13 on 2022-08-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_auto_20220501_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodesGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuses', models.TextField()),
                ('checked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
