# Generated by Django 3.2.13 on 2022-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_node_same_status_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='notified_status',
            field=models.BooleanField(default=False),
        ),
    ]
